much better ssh-agent-setup

diff --git a/doc/shell_functions/ssh-agent-setup b/doc/shell_functions/ssh-agent-setup
--- a/doc/shell_functions/ssh-agent-setup
+++ b/doc/shell_functions/ssh-agent-setup
@@ -6,7 +6,18 @@
 #
 # License: GPL
 
-SSH_AUTH_SOCK=`find /tmp -name "agent.[0-9]*" -print|sort|tail -1`
+SSH_AUTH_SOCK=`find /tmp -uid $UID -name "agent.[0-9]*" -print 2> /dev/null|sort|tail -1`
+
+clean_old_sock()
+{
+    rm -f $SSH_AUTH_SOCK
+    rmdir /tmp/ssh-* > /dev/null 2>&1
+}
+
+launch_agent()
+{
+    eval `ssh-agent -s`
+}
 
 load_keys()
 {
@@ -15,22 +26,20 @@ load_keys()
             continue
         fi
         ssh-add $key
+        rc=$?
+        if [ $rc = 2 ]; then
+            echo "Repairing ssh-agent ($rc)"
+            clean_old_sock
+            launch_agent
+            ssh-add $key
+        elif [ $rc = 1 ]; then
+            echo "Your key $key could not be loaded"
+        fi
     done
 }
 
 if [ -S "$SSH_AUTH_SOCK" ]; then
     SSH_AGENT_PID=`echo $SSH_AUTH_SOCK|cut -d. -f2`
     export SSH_AUTH_SOCK SSH_AGENT_PID
-else
-    if [ -e "$SSH_AUTH_SOCK" ]; then
-        rm -f $SSH_AUTH_SOCK
-    fi
-    # remove all empty directories
-    rmdir /tmp/ssh-* > /dev/null 2>&1
-    unset SSH_AUTH_SOCK SSH_AGENT_PID
-    #echo executing: ssh-agent -s
-    eval `ssh-agent -s`
 fi
-if [ $(ssh-add -l|grep -v 'has no identities'|wc -l) -lt 1 ]; then
-    load_keys
-fi
+load_keys
