fix: compwords is cleaner. force commits w FORCE=1 env

diff --git a/share/git-templates/hooks/pre-commit b/share/git-templates/hooks/pre-commit
--- a/share/git-templates/hooks/pre-commit
+++ b/share/git-templates/hooks/pre-commit
@@ -20,6 +20,10 @@
 branch="$(git branch --show-current 2> /dev/null || git rev-parse --abbrev-ref HEAD)"
 
 if [ "$branch" = "master" ] || [ "$branch" = "main" ]; then
-  echo "You can't commit directly to '$branch' branch"
-  exit 1
+    if [ $FORCE = 1 ]; then
+        : nothing
+    else
+        echo "You can't commit directly to '$branch' branch"
+        exit 1
+    fi
 fi
